### ISSUE TITLE
Error when open project

### ISSUE THREAD

**Issue by ashyoff** [cursiveclojure/cursive#515] opened 2014-09-26 03:53 UTC
java.lang.Double cannot be cast to java.lang.String: java.lang.Double cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at cursive.leiningen.project.LeiningenProjectsManager.getInterProjectDependencies(LeiningenProjectsManager.java:449)
	at cursive.leiningen.project.LeiningenProjectsManager.access$700(LeiningenProjectsManager.java:32)
	at cursive.leiningen.project.LeiningenProjectsManager$3.run(LeiningenProjectsManager.java:266)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:101)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by danielcompton** [comment] 2015-07-26 01:26
Do you have an example of the project to test this on?

**Comment by danielcompton** [comment] 2015-07-26 01:36
Looks like a dupe of #560.

**Comment by cursiveclojure** [comment] 2015-07-26 09:02
Looks like it.

**Closed by cursiveclojure** 2015-07-26 09:02 UTC
