### ISSUE TITLE
Reformatting code issues (white space)

### ISSUE THREAD

**Issue by yatesco** [cursiveclojure/cursive#652] opened 2014-11-24 12:41 UTC
Hi - still loving Cursive! 

Is it expected that reformatting code remove whitespace (including newlines) between closing brackets?

For example, if I have

```
(defn hi-there [person]
  (println (str "Hi there " person)

)
```

I expected reformatting to produce:

```
(defn hi-there [person]
  (println (str "Hi there " person))
```

but it doesn't, it leaves the whitespace and carriage return in-place.

Is this expected or on the future plan? I think it should as (AFAIC) this is idiomatic.

**Comment by cursiveclojure** [comment] 2015-01-05 12:38
I might make this available as an option, since it's normally idiomatic. However I sometimes leave a trailing parenthesis in e.g. lists of tests, so I can easily copy and paste a new one.

**Comment by danielcompton** [comment] 2015-07-26 10:30
Dupe of #564.

**Closed** 2015-07-26 10:31 UTC
