### ISSUE TITLE
Debugging by form/symbol?

### ISSUE THREAD

**Issue by LusciousPear** [cursiveclojure/cursive#798] opened 2015-03-19 21:09 UTC
Hi, 

New Clojure user here, and a big fan of Cursive (I've used IntelliJ forever). 

One thing that's been puzzling me -- it seems debugging breakpoints work by line, and not form/symbol. But while line breakpoints are great for java, it doesn't make much sense for Clojure, because you lose track of where you are in the execution flow, etc. 

Is there a way I can highlight a parenthesis and have that be the breakpoint, or some way to set a before/after on when a form is executed? 

(Sorry for imprecise terminology, I'm new to this)

Thanks!

**Comment by cursiveclojure** [comment] 2015-03-19 21:17
Thanks for the kind words!

Unfortunately, this is a limitation of JDI, the Java Debugging Interface. Much like stacktraces, debugging works using information in the bytecode to map bytecode back to source, and since that was designed for Java it's all line-based. Sadly, there's no way to fix this short of some complicated source-mapping technique, but that's unlikely to happen any time soon, if ever. I'll close this for now since there's no good solution for it. I'll actually be speaking at Clojure/West about this and other problems with debugging Clojure code.

**Closed by cursiveclojure** 2015-03-19 21:17 UTC
