### ISSUE TITLE
Default to .cljs files in cljs directory

### ISSUE THREAD

**Issue by savagematt** [cursiveclojure/cursive#1016] opened 2015-08-13 08:06 UTC
I create namespaces with the wrong extension every time.

I need new cljs namespaces infrequently enough that my brain isn't learning. It's a bit annoying.

**Comment by danielcompton** [comment] 2015-08-13 08:09
Duplicate of #904. Great minds think alike :)

**Comment by danielcompton** [comment] 2015-10-12 09:24
Closing as dupe of #904.

**Closed by danielcompton** 2015-10-12 09:24 UTC
