### ISSUE TITLE
Changing a submodule version causes the Run/Debug dialog to forget it

### ISSUE THREAD

**Issue by sfnelson** [cursiveclojure/cursive#507] opened 2014-09-22 04:37 UTC
Steps to reproduce:

 * Import a multimodule project
 * Create a "Run with Leiningen" Run/Debug configuration and pick a project other than the default
 * Change the version of your project
 * Sync Leiningen

Note that the Run configuration has reverted to the default project, rather than picking new version of the previous project.

**Comment by cursiveclojure** [comment] 2015-08-21 13:13
This was fixed a couple of builds ago, but I hadn't found this as a duplicate of the other issue.

**Closed by cursiveclojure** 2015-08-21 13:13 UTC
