### ISSUE TITLE
Having pom.xml alongside project.clj breaks project

### ISSUE THREAD

**Issue by katox** [cursiveclojure/cursive#646] opened 2014-11-21 08:02 UTC
If you try to reopen an existing project imported from project.clj while having there pom.xml (probably generated by "lein pom" command) things break pretty horribly within IDEA.

This is not an issue if you generate the pom while project is already open.

**Comment by danielcompton** [comment] 2015-07-26 10:17
Hmm, I can't reproduce this issue, do you have some reproduction steps including a specific project for this?

**Comment by cursiveclojure** [comment] 2015-10-22 00:07
Closing this in the absence of more reproduction information.

**Closed by cursiveclojure** 2015-10-22 00:07 UTC
Labels: Leiningen
