### ISSUE TITLE
Multi-arity defn: recursive scoping w/ conflicting var

### ISSUE THREAD

**Issue by lorddoig** [cursiveclojure/cursive#886] opened 2015-05-14 13:15 UTC
~~Despite trying, I can't reproduce this~~:

![screen shot 2015-05-14 at 13 09 47](https://cloud.githubusercontent.com/assets/3156214/7631503/118bd71a-fa3b-11e4-8de4-262882a52359.png)

~~I remember (because I thought afterwards that it shouldn't have worked) after defining the arity 1 version, I hit 'Wrap in ()' on a blank line above (between defn and the arity 1 version) instead of typing a paren and it gave me `()` instead of slurping the succeeding form.~~

The errors are for incorrect arity 1 and 0 respectively.  ~~If I delete it and recreate it with the same name `field` it happens again so the corruption is cached I guess.~~

~~This kind of thing happens all the time with other language plugins, but this is the first time I've seen it in Cursive - so~~ kudos to you!

**Comment by lorddoig** [comment] 2015-05-14 16:31
Well, well, well, aren't I quite the idiot.  Naturally, there was a conflicting arity 4 function in this file (and, naturally, I was sure I'd checked...)

Interestingly, it was near the bottom of the file.  This one was at the top.  So I suppose there is a very minor and trivial bug in that while Cursive is clever enough to know that a function is usurped by a later definition, the arity error at this point is not correct.

Changing the title, I'll leave it up to you to close it or not.

**Comment by cursiveclojure** [comment] 2015-05-14 21:19
Yeah, this is a tricky one, since the dynamic loading of Clojure means that there are various situations:
```
(defn x [a])

(defn y [] (x a))

(y)

(defn x [a b])
```
This piece of code will execute correctly, but Cursive will mark the `(x a)` as an error. Because it's impossible to know what the dynamic context is, Cursive errs on the side of the steady state - once everything is loaded, what will the behaviour be? In this case, once everything is fully loaded, calling `(y)` will provoke an error, even if the same call will work during the namespace loading process. This is probably the case for invocations of `x` from anywhere in the program except between the two definitions.

I'll close this, since it's working as designed. I'll write it off to Clojure being confusing from time to time :-)

**Closed by cursiveclojure** 2015-05-14 21:19 UTC
