### ISSUE TITLE
Refactor: Extract to namespace

### ISSUE THREAD

**Issue by markmandel** [cursiveclojure/cursive#90] opened 2013-11-05 07:46 UTC
Take a defn or def and move it to a new / existing namespace, and automatically use the correct use/require in the (ns) declaration.

(I'm sure this is tricky). 

Combined with Extract Function, this would be very powerful.

**Comment by cursiveclojure** [comment] 2015-07-26 09:00
Closing this since it's a dupe of #817, which has more detail.

**Closed by cursiveclojure** 2015-07-26 09:00 UTC
