### ISSUE TITLE
Incorrect ArityException

### ISSUE THREAD

**Issue by mtruyens** [cursiveclojure/cursive#1169] opened 2015-11-23 05:37 UTC
In a very simple Instaparse example, I get the following error message in the repl when asking for the "result" object:

Error handling response - class clojure.lang.ArityException: Wrong number of args (3) passed to: engine/annotate-rights/fn--3524

No such exception is raised when the project is run from a repl in a normal terminal -- instead, a normal parse error is given then (which is correct, because the input given to the parser does not match the grammar). 

```clojure
(ns myparser.core
  (:require [instaparse.core :as insta]))

(def as-and-bs
  (insta/parser
    "S = AB*
     AB = A B
     A = 'a'+
     B = 'b'+"))

(def result (insta/parse as-and-bs "abccccc"))
```

See example files on https://gist.github.com/anonymous/9ef9f99c94a19f84448d 

Side question: which parser did you use for your better error reporting (https://www.youtube.com/watch?v=kt4haSH2xcs)?

**Comment by cursiveclojure** [comment] 2015-11-24 02:19
Thanks for the great reproduction case. This is now fixed in the next build, but there's an additional problem. If Cursive's auto-formatting of output values is turned on, you'll get a result like the following:

```
result
=> Parseerroratline1column3:abccccc^Expected oneof:"a""b"
```

This is because the auto-fomatting needs to parse the return value, and Instaparse redefines print-method for its Failure object to print something in a non-readable way. The best workaround I can think of is to turn off the auto-formatting when working with Instaparse, which is a bummer.

@Engelberg You might be interested in this. The issue is that by redefining print-method for Failure, nREPL returns a formatted string as the value of the evaluation, rather than returning it as output. I'm not even sure if there's a bug here, but the behaviour is strange and not something I've seen before. I'm not sure what the implied contract of print-method is, if any.

**Closed** 2015-11-24 02:31 UTC

**Comment by Engelberg** [comment] 2015-11-24 04:22
`result` in the example is a Failure record, not a string.  It just happens to print differently than a typical record.  

Maybe cursive's auto-format capability could hook into the default case for print-method, and not alter anything that has a custom case for print-method?

**Comment by cursiveclojure** [comment] 2015-11-24 04:29
The problem is that the auto-formatting happens on the client side of the nREPL connection, where that information has been lost. The only thing I can think of for this would be to set `*print-dup*` which nREPL respects, but then the user will not have their Failures printed in any useful way.

**Comment by Engelberg** [comment] 2015-11-24 04:34
What I'm thinking is that maybe, instead of intercepting the output of the nREPL connection and manipulating it, Cursive could simply use defmethod to override the default case of print-method to whatever intelligent auto-formatting you want to have.  So the logic would happen on the server side of the nREPL connection, and Cursive would receive the output from the nREPL already in its desired format.

**Comment by Engelberg** [comment] 2015-11-24 04:38
Alternatively, maybe you could use get-method to determine whether a value is handled by the default print-method before intercepting the output and applying auto-formatting logic?

**Comment by Engelberg** [comment] 2015-11-24 04:40
But as far as I can tell, there's no implicit guarantee that Clojure values print readably.  The documentation example for clojure.core/print-method is, in fact, an example of altering a value to print in a non-readable way, so that would seem to support the idea that this is an intended use.

**Comment by cursiveclojure** [comment] 2015-11-25 03:58
Right, see #1176 for another case. I'm going to have to rethink this. Formatting on the server side is difficult because it's hard to syntax highlight that way - I can do it using ANSI codes but then the colours don't match what the user expects. 

I think what I'm going to do, at least initially, is try parsing the form and if the form doesn't parse as a single Clojure form just print it verbatim, otherwise I'll pretty print it.

**Comment by cursiveclojure** [comment] 2015-11-25 04:13
I've implemented this in the next build. Cursive will try to read the form as a single Clojure form, and if it can't will print it verbatim.
