### ISSUE TITLE
'Require namespace' suggestion pops up in REPL when not needed

### ISSUE THREAD

**Issue by vojtapol** [cursiveclojure/cursive#593] opened 2014-11-03 20:51 UTC
The REPL works without following the suggestion so it must be unnecessary. See attached picture to see what I mean.
![issue](https://cloud.githubusercontent.com/assets/7419355/4890032/20c6316c-639b-11e4-84cc-a3d0089a7fc3.png)

**Comment by cursiveclojure** [comment] 2015-02-05 11:09
I can't reproduce this issue - have either of you seen a pattern to when this occurs?

**Comment by d-t-w** [comment] 2015-02-05 11:13
Hey Colin, I'm watching this issue because it happens literally every time I use the REPL. Auto-import works fine, and I can execute code using the imported namespace, but cursive continues to offer to import.

I wonder if it's somehow related to lein configuration, because Dan and I were working on the same set of projects at the time he raised this ticket. For me it happens on every project, in every REPL, regardless.

Im using the latest Intellij 14 and cursive.

**Comment by cursiveclojure** [comment] 2015-02-05 11:14
Do you have a project that reproduces this issue that you can send me so I can try to see what's going on?

**Comment by cursiveclojure** [comment] 2015-02-05 11:21
BTW if you have one that's semi-sensitive that I could try, drop me a mail on cursive@cursiveclojure.com.

**Comment by d-t-w** [comment] 2015-02-06 04:04
https://github.com/d-t-w/cursive-auto-import

**Comment by cursiveclojure** [comment] 2015-02-06 06:58
Thanks to the reproduction case from @d-t-w, this is finally fixed in the next build!

**Closed** 2015-02-06 06:59 UTC
