### ISSUE TITLE
cursive does not allow removing parentheses

### ISSUE THREAD

**Issue by The-Alchemist** [cursiveclojure/cursive#1028] opened 2015-08-20 21:10 UTC
A picture is worth a thousand words, so I made a screencast:

https://www.youtube.com/watch?v=-HGBWp7GAZ8

Basically, I'm trying to change ```(new ArrayList)``` to ```(def l (new ArrayList))``` but after I type in the extra first ```(```, Cursive inserts a second ```)``` that I cannot remove.

Shouldn't it add the closing paren at the _end_ instead of right next to the first paren?

Just an idea...

**Comment by cursiveclojure** [comment] 2015-08-20 21:20
This is [Structural Editing](https://cursiveclojure.com/userguide/paredit.html). See the doc there for a description of how it works, and how to disable it if it drives you nuts. It's well worth making the effort to get used to, though.

I'll close this since it's by design - let me know if you have more questions.

**Closed by cursiveclojure** 2015-08-20 21:20 UTC

**Comment by The-Alchemist** [comment] 2015-08-20 21:26
Thank you, @cursiveclojure .  That makes sense, and I like structural editing in general, but I guess my argument is that if I have ```(new ArrayList)``` and my cursor is at position 0 and type ```(```, the result should be ```((new ArrayList))``` instead of ```() (new ArrayList)```.

I'm not sure if that's easy or hard to implement.

**Comment by cursiveclojure** [comment] 2015-08-20 21:28
It's easy to implement, but it's not always (or even usually) what you want. In that case, you want to use the Wrap with () action which will do just what you describe.

**Comment by danielcompton** [comment] 2015-08-20 21:28
@The-Alchemist I think what you're looking for is "Wrap with ()". I bind it to Option+Shift+( so it's almost the same as just making an open paren.

**Comment by The-Alchemist** [comment] 2015-08-20 21:33
@danielcompton : ah, yes, perfect, thank you!
