### ISSUE TITLE
Wrong hint "<function name> cannot be resolved" for inner functions

### ISSUE THREAD

**Issue by vasily-kirichenko** [cursiveclojure/cursive#865] opened 2015-05-03 10:28 UTC
![image](https://cloud.githubusercontent.com/assets/873919/7444676/3fbf4712-f198-11e4-8797-5288f8f70baf.png)

The code

```clojure
(defn ffib [n]
  (defn go [x n2 n1]
    (if (= x 0)
      n2
      (recur (- x 1) n1 (+ n2 n1))))
  (if (< n 2)
    n
    (go n 1 1)))
```

**Comment by cursiveclojure** [comment] 2015-05-03 20:50
Right - while this is technically legal, it's strongly discouraged. Unlike Scheme, `defn` shouldn't be used like this, since it defines a top-level var every time the function is invoked - that's almost certainly not what you want. A better solution would be to either use `letfn`, or `(let [go (fn [x n2 n1] ...`.

Since this is by design, I'll close this issue.

**Closed by cursiveclojure** 2015-05-03 20:50 UTC
