### ISSUE TITLE
Cannot start REPL

### ISSUE THREAD

**Issue by johanhaleby** [cursiveclojure/cursive#681] opened 2014-12-18 16:09 UTC
I'm using Intellij 14.0.2 and Cursive 0.1.42 and I run into the following exception when I try to start the REPL (I've loaded a Leiningen project): 

2014-12-18 17:06:28,360 [19410214]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
com.intellij.execution.ExecutionException
	at cursive.repl.runner.LocalProgramRunner$1$1.run(LocalProgramRunner.java:127)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:125)
	at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at com.intellij.execution.runners.ProcessProxyFactoryImpl.createCommandLineProxy(ProcessProxyFactoryImpl.java:34)
	at cursive.repl.runner.LocalProgramRunner$1$1.run(LocalProgramRunner.java:96)
	... 19 more

**Comment by conan** [comment] 2015-01-05 15:45
I've got a "Error running <run config name>: Unknown error" every time I try to start a REPL after upgrading to 0.1.43.  I still get the "Runner Run ..." error on the first try, this is a different issue

**Comment by cursiveclojure** [comment] 2015-01-06 03:13
@conan Can you still reproduce your issue? Or could you look back through your logs to see if there are any exceptions there?

**Comment by johanhaleby** [comment] 2015-01-06 06:05
When I said "reimported" I actually meant letting Intellij deleting the old project first just to be clear. Just reloading it didn't help me.

**Comment by conan** [comment] 2015-01-06 09:24
@cursiveclojure I can't see anything specific in the logs from yesterday, but I reported the issue here at about 15:30 yesterday my time, so I've made a gist of yesterday's log up to then: https://gist.github.com/conan/7ba76a938e482f437d25

**Comment by jdunruh** [comment] 2015-03-13 16:35
I have been able to fix the problem. I discovered I was on 0.0.48. I had done an update to 0.1.49, but it didn’t work. I could not upgrade through the repository, or by downloading and installing the file. I uninstalled 0.1.48, restarted, then added 0.1.49 and all is well. It looks like there was some sort of silent failure in the upgrade that left things in a bad state. 

I was not seeing any useful exceptions. When I did an upgrade in the plugins screen, sometimes I would see the download window, which disappeared quickly or after some time without any change to the progress bar. The version remained at 0.1.48. Sometimes I did not see the download window at all.

John Unruh
j_unruh@hotmail.com

**Comment by conan** [comment] 2015-03-24 14:58
I'm still getting a problem, but it's actually now worse.  I upgraded to Intellij 14.1 without realising I'd lose my beloved Cursive, so I downgraded back to 14.0.4.  Now Cursive 0.1.50 (which I was previously using) won't start a REPL at all, it says unknown error.  From the logs:

```
2015-03-24 14:55:41,832 [ 447891]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
com.intellij.execution.ExecutionException
	at cursive.repl.runner.LocalProgramRunner$1.run(LocalProgramRunner.java:120)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:125)
	at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.NullPointerException
	at com.intellij.execution.runners.ProcessProxyFactoryImpl.createCommandLineProxy(ProcessProxyFactoryImpl.java:34)
	at cursive.repl.runner.LocalProgramRunner$1.run(LocalProgramRunner.java:89)
	... 19 more
```

**Comment by cursiveclojure** [comment] 2015-03-24 21:18
That's bad. Note that you can use Cursive with 14.1, you just have to change your plugin repo path as described [here](https://cursiveclojure.com/userguide/). Does that help?

**Comment by conan** [comment] 2015-03-25 09:23
No, I tried using the new repo and installing from disk in 14.1 and neither would work, so I'm back on 14.0.4 for now.

**Comment by cursiveclojure** [comment] 2015-03-25 22:12
BTW let me know if you're still having that REPL problem on v14.1, too.

**Comment by conan** [comment] 2015-03-26 09:46
Yes, although now I can't start one at all, whereas I used to get one shot before it broke.

**Comment by cursiveclojure** [comment] 2015-03-26 10:24
Hmm. So if this happened in `0.1.49` and `0.1.50`, it's probably because of the lein upgrade. Is this a lein REPL? Anything unusual about the project or the run config? Can you run other REPLs, is it just this config that's broken?

**Comment by cursiveclojure** [comment] 2015-03-26 10:36
Actually, assuming it's a lein REPL, could you check your run config and make sure that the specified lein project is added, i.e. that it appears in the Leiningen toolwindow? For some reason the lein projects can get lost, and it seems to happen particularly when switching versions. It happens to me a lot because I bounce between versions all the time, but I've never managed to track the problem down. If not, re-adding it should hopefully fix this problem.

**Comment by conan** [comment] 2015-03-26 11:23
Well that's the thing, I don't seem to have a leiningen tool window any more.  How would I usually go about opening it?  It doesn't appear in View > Tool Windows, and it's not in my tool window bar like usual.

The Run config is a pretty standard Clojure REPL, I specify one `-D` jvm arg, but the problem happens without that.  Apart from that I'm just making and synchronising.  Same problem in both a clj project and a cljs one.

**Comment by conan** [comment] 2015-03-26 11:25
Here's an interesting thing I hadn't spotted before, it doesn't come up when I trigger a run, but it's sitting there in the error window:

` Throwable: Conflicting component name 'LeiningenRunnerSettings': class cursive.leiningen.run.LeiningenRunnerSettings and class de.janthomae.leiningenplugin.run.LeiningenRunnerSettings`

That's probably responsible for my leiningen tool window not existing.  This is a fresh install, but the run configs are still in my profile.

**Comment by cursiveclojure** [comment] 2015-03-26 11:26
That looks to me like you have the original Leiningen plugin installed - is that the case? You'll want to remove it if so.

**Comment by conan** [comment] 2015-03-26 11:28
Yep ok, removed that and it's restored my leiningen tool window.  Now I get this when trying to run a REPL:

`11:27:30 Error running backend REPL : java.lang.ClassNotFoundException: java.nio.file.FileSystems, compiling:(leiningen/less/nio.clj:1:1)`

**Comment by cursiveclojure** [comment] 2015-03-26 11:33
So now that you have your tool window back, your project appears there, right?

That error appears to be something to do with [lein-less](https://github.com/montoux/lein-less). At a guess, I'd say that it requires Java 7, and you're running IntelliJ on Java 6. Is that right?

**Comment by conan** [comment] 2015-03-26 16:12
Nailed it!  Switched Intellij to Java 7 and it's fixed, thanks for your help.  Incidentally Intellij still claims not to support Java 7, but it seems to work fine for me.

**Comment by cursiveclojure** [comment] 2015-03-26 21:56
That `clj` error is weird, I've seen that in several contexts, normally CLJS actually. There's at least one bug against ClojureScript itself with that message, I'm not sure what the root problem is. Does it prevent you running the REPL?

The JDK story for IntelliJ is long, complicated and sad, and there's no right option at the moment. You have to pick the JDK which annoys you the least, basically. A good option to try would be the custom JDK 8 from JetBrains, you can get versions of IntelliJ with that bundled with it.

**Comment by cursiveclojure** [comment] 2015-03-26 22:03
Also, have you recently added lein-less to your project, or did that work previously with versions prior to `0.1.49`? It's possible the lein upgrade has changed when plugins are invoked in lein.

**Comment by conan** [comment] 2015-03-27 14:26
lein-less has been there for a while (maybe 3-4 weeks), and with your hectic release schedule that must mean it was working prior to `0.1.49`.

**Comment by cursiveclojure** [comment] 2015-03-29 00:13
Ok, since this is working now, I'm going to close it.

**Closed by cursiveclojure** 2015-03-29 00:13 UTC

**Comment by dustingetz** [comment] 2015-05-11 18:22
I get this same error `java.lang.ClassNotFoundException: java.nio.file.FileSystems, compiling:(leiningen/less/nio.clj:1:1)`. Cursive 1.54, just upgraded to Intellij 14.1 Ultimate, I do not have leiningen intellij plugins installed. I do use `lein-less` leiningen plugin. Java 1.8.20, but project-level is set to 1.7.

**Comment by cursiveclojure** [comment] 2015-05-11 20:24
@dustingetz  Yeah, assuming you're on OSX you'll have to change the JDK that IntelliJ uses. Since Cursive runs lein in-process it doesn't use the project JDK for invoking lein. A fix for this is planned but for now the best thing to do is to run IntelliJ under a later JDK. Unfortunately Oracle have made a total hash of this and later JDK versions have pretty bad bugs. The best option is to download a copy of IntelliJ using their bundled custom JDK which fixes some of them, but that may only be for their EAP releases (see [here](https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP)).

Sorry about this - the only consolation is that Apple's JDK6 now has pretty bad bugs under Yosemite, so soon all the options will be equally bad.

**Comment by dustingetz** [comment] 2015-05-11 20:48
What changed over the weekend? Everything worked fine last week.

**Comment by cursiveclojure** [comment] 2015-05-11 20:57
That I don't know. I'd guess that the upgrade changed the JDK version that IntelliJ is using, but I can't explain how your v14.1 CE installation might have broken.
