### ISSUE TITLE
Cursive 0.1.51 is incompatible with IntelliJ IDEA 14.1 (build from March 23)

### ISSUE THREAD

**Issue by bilus** [cursiveclojure/cursive#813] opened 2015-03-30 10:05 UTC
After the upgrade Preferences > Plugins list Cursive as "incompatible with current IntelliJ IDEA installation" and the plugin no longer works.

**Comment by cursiveclojure** [comment] 2015-03-30 10:07
When upgrading to IntelliJ 14.1, you have to change your plugin repository, as explained [here](https://cursiveclojure.com/userguide/).

**Comment by bilus** [comment] 2015-03-30 10:10
Thank you for a super quick reply.

Pretty non-intuitive. I remember reading the doc months ago when I
originally installed the plugin but right now, it just stops working after
the upgrade. Suggestion: perhaps it's possible for the plugin to check the
current version of the IDE and show a message that points to the document
when the version is incompatible?

**Comment by cursiveclojure** [comment] 2015-03-30 10:39
Yeah, this is a problem. There's actually a new-format repo format which would allow multiple versions in the same file, but I couldn't get it to work (see https://youtrack.jetbrains.com/issue/IDEA-137274 for lots of boring detail - tldr is that I have problems with it that JetBrains can't reproduce).

Anyway, I'm working on it, it'll get fixed at some point. I'll close this in the meantime.

**Closed by cursiveclojure** 2015-03-30 10:39 UTC
