### ISSUE TITLE
Clojure keybinding not taking precedence

### ISSUE THREAD

**Issue by neverfox** [cursiveclojure/cursive#985] opened 2015-07-25 04:42 UTC
In the user's guide it says "The Cursive actions will take priority in Clojure contexts but will not execute in other contexts" and that was once the case. However, recently, option-R (OS X), which I have mapped to "Raise" as part of the Emacs profile gives me the IntelliJ search history (which was the noted conflict). I cannot say if this is just a problem with this one binding or all bindings with conflicts. This is just the one I noticed. IntelliJ 1.14.1, Java 1.8.0_51-b16, and Cursive 0.1.58.

**Comment by cursiveclojure** [comment] 2015-07-26 10:19
I can't reproduce this issue. I mapped Raise as you describe but it always works correctly, and debugging the code it is correctly promoting the Clojure action above the others. Is there a specific context (REPL editor, or some other specialised editor) in which you see this problem?

**Comment by cursiveclojure** [comment] 2015-07-27 11:55
I'd like to fix this issue for the next build which I'm going to bring out shortly - do you have any more information?

**Comment by neverfox** [comment] 2015-07-27 15:09
Okay I figured out what's happening. It works when you first open a project. But once I start a REPL, it stops working (this is in both the file editor and the REPL input).

**Comment by cursiveclojure** [comment] 2015-07-27 15:23
Interesting, thanks. I just brought out the next release, but if I can reproduce this it'll definitely be in the following one.

**Comment by cursiveclojure** [comment] 2015-07-27 15:54
I just tried to reproduce this again but couldn't. I also can't imagine any way that this could happen. It should certainly be totally independent of the REPL. Is there anything unusual in the way you're running the REPL? Does this happen on all projects?

**Comment by neverfox** [comment] 2015-07-27 16:27
I made [a screencast](https://www.dropbox.com/s/yybimspt6hi98a0/cursive-raise.mov?dl=0) showing the issue, if that's helpful. Let me know if you see anything non-standard that I'm doing.

**Comment by cursiveclojure** [comment] 2015-07-28 09:08
Thanks for the screencast - that does indeed make it clearer. What you're seeing there is not actually the IntelliJ search history - sorry, I didn't read your initial message carefully enough, I thought you were using Command-R. That's actually the Cursive "Search REPL history" action, which allows you to search previous commands you've entered into the REPL. Since both of these commands are Clojure-specific, Cursive can't disambiguate between them. You always get Raise before the REPL is running since you can't search the REPL history until you have a REPL, obviously.

I'm going to close this since it's not actually a bug - I'd recommend remapping "Search REPL history", since I assume you use Raise more frequently.

Thinking about it after the fact, a good way to diagnose this would have been to use the Find Actions by Shortcut button in the Keymap panel, which would have made it clear which actions conflicted.

As an aside, see [#326](https://github.com/cursiveclojure/cursive/issues/326) and the linked [#38](https://github.com/cursiveclojure/cursive/issues/38) for how to trick Cursive into resolving the Datomic symbols correctly.

**Closed by cursiveclojure** 2015-07-28 09:08 UTC
Labels: bug

**Comment by neverfox** [comment] 2015-07-28 14:31
Ah, I see. Glad to understand what's going on and it's not a bug. However, since this is caused by a conflict that's present in the binding included with Cursive that it should be resolved so that it's internally free of conflicts?

**Comment by cursiveclojure** [comment] 2015-07-28 14:37
Yes, definitely, that's one that I had missed. Interestingly, I had copied those directly from the Emacs shortcuts. It looks like REPL history is also bound to Alt-S, so I'll remove the Alt-R binding there.

**Comment by neverfox** [comment] 2015-07-28 14:38
:+1:
