### ISSUE TITLE
0.1.44 does not work with IJ 14.1 EAP

### ISSUE THREAD

**Issue by fbellomi** [cursiveclojure/cursive#724] opened 2015-02-04 11:57 UTC
"incompatible with current IntelliJ installation"

**Comment by cursiveclojure** [comment] 2015-02-04 11:57
Argh, they're killing me - another branch....

**Comment by rbeesley** [comment] 2015-02-05 11:43
I'm also having problems getting it to install on 14.0.3. It won't install from the repository link, and it won't "stay" installed from having downloaded the plugin directly.

I'm not sure if this is related, or a different issue.

**Comment by cursiveclojure** [comment] 2015-02-05 11:46
@rbeesley This is almost certainly a different issue. When you say it won't stay installed, what do you mean? What happens?

**Comment by rbeesley** [comment] 2015-02-05 11:52
If I try to install from the repository link, it flashes quickly, doesn't download, and clearly doesn't install. It does not even provide an option to uninstall.

If I try to install from the downloaded .zip file (cursive-14-0.1.44.zip), it will install so that I have an uninstall button, it will be listed as a plugin, and I will have to restart. When I load IntelliJ again, Cursive is not listed as a plugin. Going through the aforementioned steps, it just repeats the result, requiring me to install and restart again to no avail.

This is running on Windows 10 Pro Technical Preview build 9926, but this failure seems very specific to the Cursive plugin, so I'm not sure that is a related factor.

**Comment by cursiveclojure** [comment] 2015-02-05 11:54
Do you have La Clojure, the plugin from JetBrains, installed? If not, can you send me a copy of your log? Help->Show log in Explorer, mail to cursive@cursiveclojure.com.

**Comment by rbeesley** [comment] 2015-02-05 12:00
Crud! Yes, I do. I did an update of IntelliJ yesterday and I guess that got readded. I had Cursive running previously so I didn't even look for La Clojure. The repository still won't install, but I was able to install it now using the direct download. Sorry for the trouble.

**Comment by cursiveclojure** [comment] 2015-02-05 12:01
Yeah, there are some problems with the repo that I can't figure out since I can never reproduce them. Anyway, glad it's working now!

**Comment by conan** [comment] 2015-03-24 14:46
I just upgraded to 14.1 and then found this page...
So I downgraded back to 14.0.4, switched back to the `https://cursiveclojure.com/plugins-14.xml` repo, but it's still telling me that 0.1.50 is not compatible with my current Intellij version.  Is there something else I need to do?

**Comment by dmcollie** [comment] 2015-03-24 17:55
![screen shot 2015-03-24 at 17 51 24](https://cloud.githubusercontent.com/assets/209158/6808917/dbc7d9b2-d24e-11e4-8200-f704e5cf576f.png)

I updated to IntelliJ14.1 on OS X 10.10 and then updated the Cursive repo to the new 14.1 version. However IntelliJ doesn't seem to recognise any plugins associated with the repo (see attached image).

**Comment by cursiveclojure** [comment] 2015-03-24 21:24
It's interesting that it does seem to see the plugin (since it appears in the right pane there) but doesn't let you download it? It's very strange. What seems to be the most reliable method is downloading the plugin manually and installing from disk once, and then after that it works. I'm sorry, I have no idea why this is so painful.
Download the plugin from here: https://cursiveclojure.com/cursive-14.1-0.1.50.zip

**Comment by conan** [comment] 2015-03-25 09:21
On 14.1 using the 14.1 repo the left pane in @dmcollie's image above says it's not compatible if you hover.  I tried downloading the archive and installing from disk, but Intellij wouldn't have it - it just refused to do anything at all, so I assumed it didn't find any compatible plugins in the archive either.

**Comment by cursiveclojure** [comment] 2015-03-25 09:24
When you say you downloaded the archive, do you mean the plugin I linked to above? That's very strange - can you send a copy of your log to cursive@cursiveclojure.com? I'm using 14.1 and I know a lot of other users are too, there must be something simple going wrong.

**Comment by conan** [comment] 2015-03-25 09:33
Yes, I downloaded the plugin zip file and used Intellij's "Install plugin from disk".  Maybe I did it wrong, I'll try again

**Comment by cursiveclojure** [comment] 2015-03-25 09:34
Ok, if it doesn't work when you try again could you mail the 14.1 log after the attempt, and I'll see if there's anything going on there?

**Comment by conan** [comment] 2015-03-25 11:49
Turns out it was my mistake.  Intellij doesn't seem to be able to make plugin modifications whilst indexing, and having just installed the new version of Intellij the indexing was taking a while.  I made myself a cup of coffee during indexing after a re-install, and after it completed the plugin repo worked fine (I assume the install from disk would be fine then also).  Sorry!

**Comment by cursiveclojure** [comment] 2015-03-25 22:12
Oh - it's very strange that it didn't give you a popup saying you can't do that, IntelliJ is normally pretty good about that. Sorry for the hassle, the plugin installation process is not the smoothest :(

**Comment by conan** [comment] 2015-03-26 09:44
That's ok, the environment is!

**Comment by cursiveclojure** [comment] 2015-03-29 00:13
Closing this since it seems to be working now.

**Closed by cursiveclojure** 2015-03-29 00:13 UTC

**Comment by conan** [comment] 2015-03-30 16:15
Yes, sorry, thanks very much for your help.

**Comment by razvan-panda** [comment] 2015-06-03 22:51
Had a similar problem and the fix was to uninstall La Clojure. Just disabling it was not enough.
