### ISSUE TITLE
Cannot synchronise leiningen projects when cider-nrepl is in profiles.clj

### ISSUE THREAD

**Issue by markjfisher** [cursiveclojure/cursive#1114] opened 2015-10-22 09:40 UTC
Mac OSX 10.10.5
Cursive for IntelliJ 14.1 (fresh install)
IntelliJ version 14.1.5
JDK: 1.6/7/8 (tried them all)

I'm getting this error when importing a clean lein project (lein new foobar):

    Error reading /Users/xxx/IdeaProjects/foobar/project.clj
    java.lang.IllegalArgumentException: 
    No implementation of method: :urls of protocol:
    #'mranderson045.javaclasspath.v0v2v2.clojure.java.classpath/URLClasspath
    found for class: com.intellij.util.lang.UrlClassLoader, compiling:(track_state.clj:57:8) 
    No implementation of method: :urls of protocol:
    #'mranderson045.javaclasspath.v0v2v2.clojure.java.classpath/URLClasspath
    found for class: com.intellij.util.lang.UrlClassLoader

The project view shows only the root level files, and no subdirs (e.g. 'src').

When editing any file in the imported project it immediately pops up with the "Non project files access" dialog.

**Comment by cursiveclojure** [comment] 2015-10-22 09:44
What is `mranderson045`? Do you have something in your profiles that might be using that?

**Comment by cursiveclojure** [comment] 2015-10-22 09:49
It appears to be the jar packaging tool used by CIDER: https://github.com/benedekfazekas/mranderson. I guess you have something in your `.lein/profiles.clj` using this? Can you post your profiles file so I can try to reproduce?

**Comment by markjfisher** [comment] 2015-10-22 09:53
yes, here it is:

    {:user
     {:plugins [;; add plugins for all projects below
                [cider/cider-nrepl "0.10.0-SNAPSHOT"]
                [lein-localrepo "0.5.3"]
                [lein-pprint "1.1.1"]
                ]
      :dependencies [;; add deps for all projects below
                     ;; [org.clojure/tools.nrepl "0.2.7"]
                     [org.clojure/tools.nrepl "0.2.10"]
                     [spyscope "0.1.5"]]
      :injections [(require 'spyscope.core)]
      }
    }

**Comment by markjfisher** [comment] 2015-10-22 09:56
moving the profiles.clj out the way temporarily did allow me to open the project next time i opened intellij, and then moving it back gives the error again, but at least the project is editable for now.

**Comment by cursiveclojure** [comment] 2015-10-22 10:15
If you remove cider-nrepl from your profiles file, it will work. I'll investigate this, but that's the best workaround for now while working with Cursive. Cursive will work fine without it.

**Comment by markjfisher** [comment] 2015-10-22 10:42
thanks for looking into it.

**Comment by cursiveclojure** [comment] 2015-10-22 10:45
This is tricky. The problem is in clojure.java.classpath - it assumes that every classpath on the hierarchy is a URLClassLoader, or can have the c.j.c protocol extended to it. In this case, since Cursive now runs lein inside an isolated classloader that is not true, and the protocol cannot be extended to the relevant classloader because it's not available inside the shim. I'm going to file some bugs over there and see what happens.

**Comment by cursiveclojure** [comment] 2015-10-22 11:14
Reported at [CLASSPATH-7](http://dev.clojure.org/jira/browse/CLASSPATH-7).

**Comment by cursiveclojure** [comment] 2015-10-22 11:50
@markjfisher Thanks, I've edited the title since the problem is actually slightly worse, it's not just when importing. Hopefully this will get fixed upstream quickly.

**Comment by cursiveclojure** [comment] 2015-10-23 01:27
I managed to work around this problem, it will be fixed in the next build.

**Closed** 2015-10-23 05:24 UTC

**Comment by markjfisher** [comment] 2015-10-23 07:28
Confirmed. Thanks for looking into this.

**Comment by cursiveclojure** [comment] 2015-10-23 07:35
Great, thanks for letting me know.
