### ISSUE TITLE
support visual test markers for `clojure.test/are`

### ISSUE THREAD

**Issue by cprice404** [cursiveclojure/cursive#339] opened 2014-04-19 20:13 UTC
Is there any way that you could make the 'run tests in repl' action draw the green/yellow/red bubbles for the passing/failing arguments in a clojure.test/are expression?

**Comment by danielcompton** [comment] 2015-07-25 23:48
Looks like a dupe of #221.

**Closed** 2015-07-26 08:50 UTC
