### ISSUE TITLE
Deleting parenthesis not working

### ISSUE THREAD

**Issue by macdevign** [cursiveclojure/cursive#1032] opened 2015-08-22 16:38 UTC
Parenthesis deletion is not working

To replicate, enter
(+ 1 2 3)
move to the last closing parenthesis and press backspace, parenthesis will not be deleted.

running under Mac Yosemite
Intellij 14 and 15EAP have the same issue.

This bug is very annoying.

**Comment by danielcompton** [comment] 2015-08-22 19:31
This is almost certainly structural editing. #1028 has the same issue. Copying Colin's quote from there:

> This is [Structural Editing](https://cursiveclojure.com/userguide/paredit.html). See the doc there for a description of how it works, and how to disable it if it drives you nuts. It's well worth making the effort to get used to, though.

**Comment by cursiveclojure** [comment] 2015-08-22 20:50
That's right, this is by design. I'll close this.

**Closed by cursiveclojure** 2015-08-22 20:50 UTC

**Comment by macdevign** [comment] 2015-08-23 03:17
That's great to know that this is not a bug but it is by design. 

Still I wonder if the design can go by "Principle of least astonishment" https://en.wikipedia.org/wiki/Principle_of_least_astonishment . 

Suggestions:

Structural Editing for is disabled by default
or 
Place a note at https://cursiveclojure.com/ saying that such is the default behaviour for deletion.
or 
Structural Editing is Enabled by default but adding a checkbox for Freeform Deletion Parenthesis enabled. As far as I notice, Intellij allows freeform deletion of anything.

In fact in past numerous times of using Structural Editing,  I go back to using La Clojure since it simply work ( freeform  parenthesis deletion) , wondering at time if there is bug in cursive.

thank :}
