### ISSUE TITLE
Working directory for project.clj itself

### ISSUE THREAD

**Issue by juskrey** [cursiveclojure/cursive#882] opened 2015-05-11 08:19 UTC
Currently such constructions in project.clj as
```clojure
:jvm-opts ~(read-string (slurp "jvm-options.edn"))
```
are not possible because working directory while loading project.clj is somewhere in the IDEA internals.

Is it possible to handle that correctly?

Thanks!

**Comment by danielcompton** [comment] 2015-07-26 21:10
Relates to (dupe of?) #333.

**Comment by cursiveclojure** [comment] 2015-07-26 21:24
Yeah, I'll close this one since the issue is the same.

**Closed by cursiveclojure** 2015-07-26 21:24 UTC
